# Convulation and Blurring


In [1]:
import cv2 as cv
import numpy as np

In [5]:
image = cv.imread("./images/elephant.jpg")
cv.imshow("Original image", image)
cv.waitKey()
cv.destroyAllWindows()

In [17]:
image = cv.imread("./images/elephant.jpg")

#creating a 3*3 Kernel
k1 = np.ones((3, 3), np.float32)/9
print(k1)
blur_img1 = cv.filter2D(image, -1, k1)
cv.imshow("Blur with 3*3 kernel", blur_img1)
cv.waitKey()

cv.destroyAllWindows()

[[ 0.11111111  0.11111111  0.11111111]
 [ 0.11111111  0.11111111  0.11111111]
 [ 0.11111111  0.11111111  0.11111111]]


In [19]:
#creating a 6*6 Kernel
k2 = np.ones((6, 6), np.float32)/36
blur_img2 = cv.filter2D(image, -1, k2)
cv.imshow("Blur with 6*6 kernel", blur_img2)
cv.waitKey()

cv.destroyAllWindows()

In [18]:
#creating a 14*14 Kernel
k3 = np.ones((14, 14), np.float32)/196
blur_img3 = cv.filter2D(image, -1, k3)
cv.imshow("Blur with 14*14 kernel", blur_img3)
cv.waitKey()

cv.destroyAllWindows()

## Other commonly used blurring effects

In [37]:
image = cv.imread("./images/elephant.jpg")
# Averaging done by convolving the image with a normalized box filter. 
# This takes the pixels under the box and replaces the central element
# Box size needs to odd and positive 
blur = cv.blur(image, (5,5))
cv.imshow("using Blur", blur)
cv.waitKey()
cv.destroyAllWindows()


In [39]:
image = cv.imread("./images/elephant.jpg")
# Instead of box filter, gaussian kernel
guassian = cv.GaussianBlur(image, (5,5), 0)
cv.imshow("using GaussianBlur", guassian)
cv.waitKey()
cv.destroyAllWindows()


In [42]:
image = cv.imread("./images/elephant.jpg")
# Takes median of all the pixels under kernel area and central 
# element is replaced with this median value
median = cv.medianBlur(image, 5)
cv.imshow('Median Blurring', median)
cv.waitKey(0)
cv.destroyAllWindows()

In [41]:
image = cv.imread("./images/elephant.jpg")
# Bilateral is very effective in noise removal while keeping edges sharp
bilateral = cv.bilateralFilter(image, 9, 75, 75)
cv.imshow('Bilateral Blurring', bilateral)
cv.waitKey(0)
cv.destroyAllWindows()

## Image De-noising - Non-Local Means Denoising

In [44]:
import numpy as np
import cv2

image = cv2.imread('images/elephant.jpg')

# Parameters, after None are - the filter strength 'h' (5-10 is a good range)
# Next is hForColorComponents, set as same value as h again
# 
cv.imshow("Orignal image", image)
cv.waitKey()

dst = cv2.fastNlMeansDenoisingColored(image, None, 6, 6, 7, 21)

cv2.imshow('Fast Means Denoising', dst)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
**There are 4 variations of Non-Local Means Denoising:**

- cv2.fastNlMeansDenoising() - works with a single grayscale images
- cv2.fastNlMeansDenoisingColored() - works with a color image.
- cv2.fastNlMeansDenoisingMulti() - works with image sequence captured in short period of time (grayscale images)
- cv2.fastNlMeansDenoisingColoredMulti() - same as above, but for color images.