In [1]:
import cv2 as cv
import numpy as np

In [5]:
M = np.ones((5, 5), dtype = "uint8")*10
print(M)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [12]:
# arithmething operation with brightness of the image
image = cv.imread("./images/input.jpg")

M = np.ones(image.shape, dtype = "uint8")*150 # NOte that image can be max [255, 255, 2]

added = cv.add(image, M)
cv.imshow("After adding M matrix", added)
cv.waitKey()

subtract = cv.subtract(image, M)
cv.imshow("After sub M matrix", subtract)
cv.waitKey()

cv.destroyAllWindows()


# BItwise operation and masking



In [28]:
img = np.zeros((300, 300), "uint8") # making a 2d array of all zeroes and of size 300*300
rectangle = cv.rectangle(img, (50, 50), (250, 250), 255, -1)
cv.imshow("Rectangle", img)
cv.waitKey()

img = np.zeros((300, 300), "uint8") # making a 2d array of all zeroes and of size 300*300
ellipse = cv.ellipse(img, (150, 150), (150, 150), 30, 0, 180, 255, -1)
cv.imshow("Ellipse", img)
cv.waitKey()

cv.destroyAllWindows()

In [29]:
And = cv.bitwise_and(rectangle, ellipse)
cv.imshow("Bitwise AND", And)
cv.waitKey()

Or = cv.bitwise_or(rectangle, ellipse)
cv.imshow("Bitwise OR", Or)
cv.waitKey()

Not = cv.bitwise_not(rectangle)
cv.imshow("Bitwise NOT of rectangle", Not)
cv.waitKey()

Xor = cv.bitwise_xor(rectangle, ellipse)
cv.imshow("Bitwise XOR", Xor)
cv.waitKey()

cv.destroyAllWindows()